### ISSUE TITLE
Should portfinder also have a getPortsPromise function?

### ISSUE THREAD

**Issue by gaggle** [http-party/node-portfinder#102]
I use `getPortPromise` but was surprised there's no `getPortsPromise` (plural, to get multiple ports). Do you want one added?

**Comment by eriktrom** [comment]
sounds good in practice, but the complications in the code within this library require a new version before this (legit) ask be worked on - else were at the mercy of the indeterminism inherent  current os scheduling and resource allocation/deallocation through the kernel

**Comment by eriktrom** [comment]
@gaggle See my comment on pr #105 which contains a proposal that if gains traction, would allow experimentation of this idea as well as other ideas requested by others.

**Comment by eriktrom** [comment]
closing to cleanup issue list, comments or questions still welcome, if needed
