### ISSUE TITLE
Free port still in use

### ISSUE THREAD

**Issue by sla89** [http-party/node-portfinder#104]
Hello together,

I am facing the problem that portfinder is blocking a free port because the callback is called directly after calling `server.close()`. 

The problem is that  `server.close()` is an asynchronous operation and as long as the  `close` event is not emitted the port is still used by the server (Node API docs: https://nodejs.org/docs/latest/api/net.html#net_server_close_callback):

```
server.close([callback])[src]#
Added in: v0.1.90
callback <Function> Called when the server is closed
Returns: <net.Server>
Stops the server from accepting new connections and keeps existing connections.
This function is asynchronous, the server is finally closed when all connections are
ended and the server emits a 'close' event. The optional callback will be called once
the 'close' event occurs. Unlike that event, it will be called with an Error as its only
argument if the server was not open when it was closed.
```

This is where the problem happens:
https://github.com/http-party/node-portfinder/blob/master/lib/portfinder.js#L42

With regards,
Stefan

**Comment by rathboma** [comment]
I am also having this issue as I am immediately starting a server to provide SSH tunnel access, and every now and then it fails due to the port not being available.

**Comment by eriktrom** [comment]
> The problem is that server.close() is an asynchronous operation and as long as the close event is not emitted the port is still used by the server (Node API docs:

> I am also having this issue as I am immediately starting a server to provide SSH tunnel access, and every now and then it fails due to the port not being available.

When using async i/o, which was introduced along with OS scheduling (by different names, depending on the OS) -- one of the downsides is that it is up to the operating system to handle such things. The os will ask the kernel for permission to both open and close a file descriptor, and upon giving permission to open a file descriptor, the os will schedule to do so with a priority. The same goes for free'ing a file descriptor, of which http/sockets are bound to. 

thus, tl;dr - besides being strongly and thus correctly ordered (on x86) - there is no way to know exactly when the release of the file descriptor will occur, be cleaned up, and known to the kernel to be available for use again.

that's the tl;dr - the longer story is much more complicated.

my suggestion is to poll and use a Promise wrapping setTimeout/setInterval. You can wrap the interval in a promise, when it rejects, recurse, when it succeeds, clear the interval, use the port.

Let me know if you have further questions, sorry for the delay here!

**Comment by eriktrom** [comment]
closing to cleanup issue list, comments or questions still welcome, if needed
