### ISSUE TITLE
migrate to mkdirp v1

### ISSUE THREAD

**Issue by Hypnosphi** [http-party/node-portfinder#112]
npm says that mkdirp v0.x has been deprecated: 

```
npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
```

**Comment by jimmywarting** [comment]
how about dropping it and use nodes built in mkdir instead?

**Comment by mfranzke** [comment]
Or use https://www.npmjs.com/package/make-dir instead.

**Comment by eriktrom** [comment]
> how about dropping it and use nodes built in mkdir (recursive option) instead?

we have to support node 0.10.x - that said - neither of the above (built in mkdir or promises) can be merged in...

is there a security issue here or just 'lets keep node modern' which is totally legit, just not with this lib unfortunately

open to discussion if there is a reason outside of staying modern...

**Comment by Hypnosphi** [comment]
> lets keep node modern

it's rather 'lets not depend on deprecated things'

**Comment by jimmywarting** [comment]
... and use less dependencies and marketing it smaller

**Comment by eriktrom** [comment]
I actually feel the same way and have opened an issue (that I need to clean up b/c it was a brain dump) #122 

perhaps it should just say: 

> 'lets not depend on deprecated things'

at least that's what I am trying to say, in a very round about way :)

**Comment by Glandos** [comment]
mkdirp has a new 0.5.6 version with updated minimist dependency. It should fix the issue for now.

**Comment by eriktrom** [comment]
@see https://github.com/http-party/node-portfinder/issues/131

also minimist has been updated tonight, it will go out in the next release this week.
