### ISSUE TITLE
Please update mkdirp from 0.5.5 to 0.5.6

### ISSUE THREAD

**Issue by nemeseri** [http-party/node-portfinder#125]
Mkdirp 0.5.5 uses minimist as a dependency and 1.2.5 has a vulnerability:
Minimist <=1.2.5 is vulnerable to Prototype Pollution via file index.js, function setKey() (lines 69-95).

**Comment by ChocolateLoverRaj** [comment]
I think mkdirp should be updated to v1

**Comment by eriktrom** [comment]
closing see #131
