### ISSUE TITLE
Find port on remote machine

### ISSUE THREAD

**Issue by tiagosiebler** [http-party/node-portfinder#71]
Would be curious if this can be adapted to find an available port on a remote machine, rather than localhost.

**Comment by eriktrom** [comment]
yeah - you can pass `host` as well as `port` - however, the host you pass in (ip or hostname) will be pushed onto an array of default hosts ([`0.0.0.0, ::1, null, "*"]` at minimum IIRC) - the port is considered 'found to be open' when `net.createServer`'s `.on('listen')` handler is called (and 2 well known errors, `'EADDRINUSE' || 'EACCES'`) are thus not thrown... 

you can get around this 'local' host constraint by overriding the `exports._defaultHosts ` private but exported method - example: `exports._defaultHosts = ['host1', '1.1.1.1`, 'anotherhost' ]`

caveat though is this block https://github.com/indexzero/node-portfinder/blob/f0f71e38e563742565006a538573076d8375a0cc/lib/portfinder.js#L187-L199

you need >= 2 hosts with the same open port for the recursion to terminate - obviously you could fork the repo and change that block of code.

other caveat is that just b/c you can listen on an interface doesn't mean it's actually open for business, if a version 2 of this lib we're ever to come about, it would be to remove the error checking and simply echo a string, see if it comes back, for a single host + port combo, which would guarantee 'its' open for business, and prevent having the aformentioned logic around checking each `exports._defaultHosts` has the same port open, as is currently done in the block of code linked to above.

(side note: that basically sums up pretty much all the logic used to find an open port in this library, which i don't think i've written anywhere, interesting)

if you hack that out, do share (same for anyone who reads this issue in future)

**Comment by eriktrom** [comment]
stale, closing

reopen if you have questions
