### ISSUE TITLE
There is more than TCP

### ISSUE THREAD

**Issue by ibc** [http-party/node-portfinder#73]
UDP exists. A port can be TCP or UDP. Perhaps the README could clarify it.

**Comment by eriktrom** [comment]
yep - pr's welcome - docs should roughly be some words + this test code: https://github.com/indexzero/node-portfinder/blob/8d0b757c3c318499f9fd1f8d865e8e7784801204/test/port-finder-socket-test.js#L30-L51

**Comment by eriktrom** [comment]
stale, closing. feel free to re-open to resume conversation.

**Comment by netstalkerr** [comment]
agree! where information that only TCP is supported??
