### ISSUE TITLE
use `neo-async` instead `async` for perf reasons

### ISSUE THREAD

**Issue by evilebottnawi** [http-party/node-portfinder#74]
I can send a PR :+1:

**Comment by eriktrom** [comment]
sorry - cleaning house - the perf characteristics of this lib will not improve given the determining factor will remain how fast node and the system can release the port after it is said to be open -- when testing many ports, this problem becomes amplified to the point where a faster async library doesn't solve much.

also, we'd have to security audit it cause well, that's become a thing these days in downstream packages like this one, which then depends on a new async lib, so on so forth. npm audit works but i don't think the perf and security are worth it

if u have good reasons that are stronger than both of those, i'm all ears.

(sorry for the delay btw, my bad)
