### ISSUE TITLE
Join http-party Github organization

### ISSUE THREAD

**Issue by indexzero** [http-party/node-portfinder#78]
Over the years I've contributed to / started / taken over several of TCP / HTTP(S) related node libraries. Each of these libraries has matured and gotten a set of independent maintainers – each with their own ebb & flow of maintenance.

In an effort to make maintaining all of these easier I created the `http-party` Github organization which I would like to add this project to. 

I've invited the current maintainer, @eriktrom, to the org and unless he feels strongly it should stay here once he accepts I'll migrate the repository over.

**Comment by eriktrom** [comment]
I accept @indexzero :)

seems good
