### ISSUE TITLE
Replace sequential scan with random search

### ISSUE THREAD

**Issue by BarthesSimpson** [http-party/node-portfinder#79]
Instead of scanning from the base port to the highest port, a randomized search would be more robust. Currently, if I am launching several servers in quick succession, there can be port collisions because one server may not have finished binding to the port discovered by portfinder before the next call to getPort, which then considers the same port to still be unbound.

**Comment by eriktrom** [comment]
> Currently, if I am launching several servers in quick succession, there can be port collisions because one server may not have finished binding to the port discovered by portfinder before the next call to getPort, which then considers the same port to still be unbound.

Yes, this an issue I am aware of. Randomizing the port scanning is an interesting idea -- open to a PR on this, thanks!

**Comment by BarthesSimpson** [comment]
(Sorry for the triplicate PR - my GitHub chops are a bit rusty)

**Comment by eriktrom** [comment]
fixed by #82
