### ISSUE TITLE
Breaking change in 1.0.22 if port is > 40000 and stopPort is not set

### ISSUE THREAD

**Issue by jelhan** [http-party/node-portfinder#85]
Default highest port was reduced in https://github.com/http-party/node-portfinder/pull/82 from `65535` to `40000`. This was discussed in https://github.com/http-party/node-portfinder/pull/82#issuecomment-520199847 and explicitly stated to be done to _not_ introduce a breaking change. But it has indeed if `getPort()` is called with `port > 40000` and without `stopPort` and without overriding `portfinder.highestPort` before. E.g. this usage:

```js
portfinder.getPort({
    port: 49741
}, callback);
```

throws

> Provided options.stopPort(40000is less than options.startPort (49741)

Noticed this breaking change by failing tests that depend on https://github.com/tomdale/ember-cli-addon-tests/issues/212.

**Comment by eriktrom** [comment]
this should be fixed, i rolled back v1.0.23 -> v1.0.21
